package model.beans;

// Generated 4-ott-2011 19.33.58 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Supervisor generated by hbm2java
 */
public class Supervisor implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String name;
	private String surname;
	private String email;
	private String type;
	private String acl;
	private Set roomsupervisors = new HashSet(0);
	private Set bookings = new HashSet(0);
	private Set timewindows = new HashSet(0);

	public Supervisor() {
	}

	public Supervisor(String username, String password, String name,
			String surname, String email, String type, String acl) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.type = type;
		this.acl = acl;
	}

	public Supervisor(String username, String password, String name,
			String surname, String email, String type, String acl,
			Set roomsupervisors, Set bookings) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.surname = surname;
		this.email = email;
		this.type = type;
		this.acl = acl;
		this.roomsupervisors = roomsupervisors;
		this.bookings = bookings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAcl() {
		return this.acl;
	}

	public void setAcl(String acl) {
		this.acl = acl;
	}

	public Set getRoomsupervisors() {
		return this.roomsupervisors;
	}

	public void setRoomsupervisors(Set roomsupervisors) {
		this.roomsupervisors = roomsupervisors;
	}

	public Set getBookings() {
		return this.bookings;
	}
	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}
	public Set getTimewindows() {
		return this.timewindows;
	}
	public void setTimewindows(Set timewindows) {
		this.timewindows = timewindows;
	}
}
