package model.beans;

// Generated 4-ott-2011 19.33.58 by Hibernate Tools 3.2.4.GA

/**
 * Booking generated by hbm2java
 */
public class Booking implements java.io.Serializable {

	private Integer id;
	private Student student;
	private Room room;
	private Supervisor supervisor;
	private String reasonBooking;
	private String date;
	private String time;
	private String reasonAnnulment;
	private String status;

	public Booking() {
	}

	public Booking(Student student, Room room, Supervisor supervisor,
			String reasonBooking, String date, String time,
			String reasonAnnulment, String status) {
		this.student = student;
		this.room = room;
		this.supervisor = supervisor;
		this.reasonBooking = reasonBooking;
		this.date = date;
		this.time = time;
		this.reasonAnnulment = reasonAnnulment;
		this.status = status;
	}
	public Booking(Student student, Room room, Supervisor supervisor,
			String reasonBooking, String date) {
		this.student = student;
		this.room = room;
		this.supervisor = supervisor;
		this.reasonBooking = reasonBooking;
		this.date = date;	
	}
	public Booking(Supervisor supervisor, String reasonBooking, String date){
		this.supervisor = supervisor;
		this.reasonBooking = reasonBooking;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public Supervisor getSupervisor() {
		return this.supervisor;
	}

	public void setSupervisor(Supervisor supervisor) {
		this.supervisor = supervisor;
	}

	public String getReasonBooking() {
		return this.reasonBooking;
	}

	public void setReasonBooking(String reasonBooking) {
		this.reasonBooking = reasonBooking;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getReasonAnnulment() {
		return this.reasonAnnulment;
	}

	public void setReasonAnnulment(String reasonAnnulment) {
		this.reasonAnnulment = reasonAnnulment;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
