package model.beans;

// Generated 4-ott-2011 19.33.58 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
public class Room implements java.io.Serializable {

	private Integer id;
	private Roomsupervisor roomsupervisor;
	private String name;
	private String topic;
	private Set roomsupervisors = new HashSet(0);
	private Set bookings = new HashSet(0);

	public Room() {
	}

	public Room(Roomsupervisor roomsupervisor, String name, String topic) {
		this.roomsupervisor = roomsupervisor;
		this.name = name;
		this.topic = topic;
	}

	public Room(Roomsupervisor roomsupervisor, String name, String topic,
			Set roomsupervisors, Set bookings) {
		this.roomsupervisor = roomsupervisor;
		this.name = name;
		this.topic = topic;
		this.roomsupervisors = roomsupervisors;
		this.bookings = bookings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Roomsupervisor getRoomsupervisor() {
		return this.roomsupervisor;
	}

	public void setRoomsupervisor(Roomsupervisor roomsupervisor) {
		this.roomsupervisor = roomsupervisor;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTopic() {
		return this.topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public Set getRoomsupervisors() {
		return this.roomsupervisors;
	}

	public void setRoomsupervisors(Set roomsupervisors) {
		this.roomsupervisors = roomsupervisors;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

}
